### ISSUE TITLE
Running the Groovy console from the groovy-all bundle does not work

### ISSUE THREAD

**Issue by pfmoore** [gradle/gradle-groovy-all#1]
If I try to run the Groovy console using the bundle generated by this project, via `java -cp .\build\artifacts\jar\groovy-all-1.0-2.5.2.jar groovy.ui.Console`, I get an error:

```
>java -cp .\build\artifacts\jar\groovy-all-1.0-2.5.2.jar groovy.ui.Console                                                  
Exception in thread "main" java.lang.NoClassDefFoundError: picocli/CommandLine$ParameterException                           
        at java.lang.Class.getDeclaredConstructors0(Native Method)                                                          
        at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)                                                   
        at java.lang.Class.getDeclaredConstructors(Unknown Source)                                                          
        at org.codehaus.groovy.reflection.CachedClass$2$1.run(CachedClass.java:88)                                          
        at java.security.AccessController.doPrivileged(Native Method)                                                       
        at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:86)                                      
        at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:81)                                      
        at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:50)                                          
        at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:37)                                                
        at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:310)                                 
        at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:218)                                                         
        at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:228)                                                         
        at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:171)          
        at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:161)         
        at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:144)                         
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:288)                               
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:331)                                        
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:270)         
        at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:976)                                   
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:86)              
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)                 
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)                 
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)                 
        at groovy.ui.Console.main(Console.groovy:203)                                                                       
Caused by: java.lang.ClassNotFoundException: picocli.CommandLine$ParameterException                                         
        at java.net.URLClassLoader.findClass(Unknown Source)                                                                
        at java.lang.ClassLoader.loadClass(Unknown Source)                                                                  
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)                                                       
        at java.lang.ClassLoader.loadClass(Unknown Source)                                                                  
        ... 24 more                                                                                                         
```

Running the same command, but using the unbundled lib directory supplied as part of Groovy works fine. The same happens with Groovy 2.5.4.

**Comment by lptr** [comment]
Yep, this won't work. We are packaging up the contents of the `groovy-*.jar`s only, but not the third-party dependencies. I guess we could be more careful, too, about what we package there, and exclude `groovy-cli-picocli.jar` and friends. The goal of this repo is to support Gradle's use of Groovy only, and the plan is to make it redundant by switching to using individual Groovy JARs instead.

**Comment by lptr** [comment]
I added this to make sure we actually implement that plan and can retire this repo: https://github.com/gradle/gradle/issues/8087

**Comment by pfmoore** [comment]
OK, thanks for the explanation.
